### ISSUE TITLE
(Refactoring) redundant check in calculation of max from 3 numbers

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#110]
**Smart-contract layer**: `VotingToManageEmissionFunds.sol`
**Problem**: https://github.com/poanetwork/poa-network-consensus-contracts/blob/security-audit/contracts/VotingToManageEmissionFunds.sol#L241-L242 - it seems, the check, that max > 0 is redundant. `max` can be greater or equal 0. 
**Solution**: suggested implementation:
```
function _max(uint256 a, uint256 b, uint256 c) private pure returns(uint256) {
    uint256 max = a;
    if (b > max) {
        max = b;
    }
    if (c > max) {
        max = c;
    }
    return max;
}
```

**Comment by rstormsf** [comment]
@varasev well, I said if it's avoidable, it's great.  if not, I don't see any issues with it.

**Comment by varasev** [comment]
Ok, I'll fix that.
