### ISSUE TITLE
(Refactoring) make getTotalNumberOfValidators private

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#115]
**Smart-contract layer**: `BallotsStorage.sol`
**Problem**: `getTotalNumberOfValidators()` is public. It is only used internal. We already have public function `getCurrentValidatorsLength()` in `PoaNetworkConsensus.sol`, which returns the number of validators.
**Solution**: let' make `getTotalNumberOfValidators()` private.

**Comment by varasev** [comment]
Fixed in #122.
