### ISSUE TITLE
(Refactoring) Modularity for calculation of validators length (including/excluding MoC)

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#116]
**Smart-contract layer**: `PoaNetworkConsensus.sol`
**Problem**: calculation of validators length is made multiple times in different places:
https://github.com/poanetwork/poa-network-consensus-contracts/blob/f53f0dce1dfac8b2fb37e73f654edff1b8187397/contracts/abstracts/VotingToChange.sol#L53-L55
https://github.com/poanetwork/poa-network-consensus-contracts/blob/f53f0dce1dfac8b2fb37e73f654edff1b8187397/contracts/BallotsStorage.sol#L103-L105
https://github.com/poanetwork/poa-network-consensus-contracts/blob/f53f0dce1dfac8b2fb37e73f654edff1b8187397/contracts/BallotsStorage.sol#L114-L116
https://github.com/poanetwork/poa-network-consensus-contracts/blob/f53f0dce1dfac8b2fb37e73f654edff1b8187397/contracts/VotingToManageEmissionFunds.sol#L175-L177
**Solution**: let's move calculation to one public method in `PoaNetworkConsensus.sol` and reuse it in those places, where we need it. `isMasterOfCeremonyRemoved` should change visibility in this case: from external to public.

**Comment by varasev** [comment]
Implemented in #122.
