### ISSUE TITLE
(Refactoring) improvements of areBallotParamsValid function

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#117]
**Smart-contract layer**: `VotingToChangeKeys.sol`
**Problem**: `areBallotParamsValid` function is hard readable
**Solution**: 
1. suggestion is to divide the logic of function to smaller internal functions
2. it seems, two `if` statements could be collapsed to one https://github.com/poanetwork/poa-network-consensus-contracts/blob/f53f0dce1dfac8b2fb37e73f654edff1b8187397/contracts/VotingToChangeKeys.sol#L30 and https://github.com/poanetwork/poa-network-consensus-contracts/blob/f53f0dce1dfac8b2fb37e73f654edff1b8187397/contracts/VotingToChangeKeys.sol#L42

**Comment by varasev** [comment]
I've already rewritten this function in #118. All conditions inside it have been grouped by ballot types and by key types: https://github.com/varasev/poa-network-consensus-contracts/blob/57fd4105075c2fb87633c73e75a3baacb7613555/contracts/VotingToChangeKeys.sol#L34-L82 - I think it's easier to read now?

**Comment by vbaranov** [comment]
Yes, it is more readable now. But I'd also suggest moving logic inside outer `if` statement to private functions like `_areKeyAddingBallotParamsValid`, `_areKeyRemovalBallotParamsValid`, `_areKeySwapBallotParamsValid`

**Comment by varasev** [comment]
Yes, I agree, I'll do.

**Comment by varasev** [comment]
Done in #122.
