### ISSUE TITLE
(Refactoring) KeysManager: limit is used without definition

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#119]
**Smart-contract layer**: `KeysManager.sol`
**Problem**: The limit is used without definition: https://github.com/poanetwork/poa-network-consensus-contracts/blob/c1fc60307e3d67a65028c7a780ece10b5b7cb32e/contracts/KeysManager.sol#L197
**Solution**: let's use `maxOldMiningKeysDeepCheck`instead

**Comment by varasev** [comment]
`KeysManager.migrateMiningKey` function at the moment of its calling knows nothing about `VotingToChangeKeys` contract which keeps that limit value.

I can add an extra `_maxMiningKeyHistoryDeep` parameter in `migrateMiningKey` function as a workaround.

We could read the limit value from the old `VotingToChangeKeys` contract and pass it as a param to `KeysManager.migrateMiningKey` function.

**Comment by vbaranov** [comment]
I am ok with `_maxMiningKeyHistoryDeep` workaround

**Comment by varasev** [comment]
Done in #122.
