### ISSUE TITLE
(Bug) KeysManager: there is no restrictions who can execute migration functions

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#120]
**Smart-contract layer**: `KeysManager.sol`
**Problem**: there is no restrictions who can execute [migrateInitialKey](https://github.com/poanetwork/poa-network-consensus-contracts/blob/c1fc60307e3d67a65028c7a780ece10b5b7cb32e/contracts/KeysManager.sol#L208) and [migrateMiningKey](https://github.com/poanetwork/poa-network-consensus-contracts/blob/c1fc60307e3d67a65028c7a780ece10b5b7cb32e/contracts/KeysManager.sol#L179) functions
**Solution**: let's restrict to contract owner

**Comment by varasev** [comment]
Fixed in #122.
