### ISSUE TITLE
Get rid of limitation when an account could receive coins only once per every block

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-network-consensus-contracts#185]
**Problem**: The current implementation in `RewardByBlock.sol` assumes that the same account could receive new coin only once per block:

https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/RewardByBlock.sol#L38-L48

Since it is assumed that bridge cannot control how fast new requests from the same account appears and this could lead that such requests need to be included in one block, the behavior described above will revert bridge's transactions.

**Solution**: to rework current implementation to allow register several requests to mint coins for the same account in one block

**Comment by varasev** [comment]
Done in #196.
