### ISSUE TITLE
Add ability to get total amount of coins minted by Block Reward feature

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-network-consensus-contracts#186]
**Problem**: Current implementation of Block Reward contracts (`RewardByBlock.sol` and `RewardByTime.sol`) does not allow to get total amount of coins minted.  

For example, this is the implementation in `RewardByBlock.sol`:
https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/RewardByBlock.sol#L73-L86

This functionality is needed by new bridge node `erc20-to-native` in order to monitor that all requests made by the bridge to mint new coins were handled properly.

**Solution**: to provide a public variable which will accumulate reward value every time when new coins are minted by Block Reward contract

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/poa-network-consensus-contracts/pull/197.
