### ISSUE TITLE
(Question) Are the deployed contracts versioned?

### ISSUE THREAD

**Issue by afck** [poanetwork/poa-network-consensus-contracts#189]
I'm trying to make [poa-ballot-stats](https://github.com/poanetwork/poa-ballot-stats) handle multiple contract versions, since it needs to be able to evaluate the network's full history, across all hard forks and contract updates.

Are there any official version numbers or identifiers to refer to the different contracts that were deployed in sokol and core? What's the best way to find out what was deployed when in both networks? Does that correspond exactly to the commits in [poa-chain-spec](https://github.com/poanetwork/poa-chain-spec)'s `sokol` and `core` branches whose commit message contains the words "hard fork"?

**Comment by varasev** [comment]
The exact tree for deployed smart contracts in the last HF for `Sokol`: https://github.com/poanetwork/poa-network-consensus-contracts/tree/6c2c7798394ed14abcfb53fe9ce6269cd83630ff

**Comment by afck** [comment]
Perfect, thank you for the quick reply!
