### ISSUE TITLE
(Update) Registration of several bridge in RewardByBlock

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-network-consensus-contracts#200]
Now only one bridge contract is possible to register in the `RewardByBlock` contract.
But it is possible such network configuration when several bridges working stable coins send requests to mint coins. 

Please consider to have the following methods:
  * `addBridgeContract` - to provide opportunity to add a new bridge contract;
  * `removeBridgeContracts` - to remove the bridge contract;
  * `mintedByBridge` - to get overall amount of tokens minted by the particular bridge.
  * what could be also useful?

**Comment by varasev** [comment]
@akolotov we have to decide who will have a permission to call these functions. Do you have any suggestions about that?

**Comment by akolotov** [comment]
@varasev I have not found a part of code which allow to set the bridge contract. My understanding now is that it is done by the upgrading the whole `RewarByBlock` contract. Could `addBridgeContract` and `removeBridgeContract` be called in similar manner? It is up to you to implement the ability to control multiple bridge contracts in order to not spoil the current security model.

**Comment by varasev** [comment]
> My understanding now is that it is done by the upgrading the whole RewarByBlock contract.

Now, the value of `bridgeContract` constant may only be changed by changing the implementation of RewardByBlock. It is possible with `VotingToChangeProxyAddress` contract, so validators should vote for the change.

We could make another type of voting to add/remove bridge contract address to RewardByBlock. @igorbarinov what can you say about it?

An easier way is to allow these functions to be called only by some Multisig Wallet.

Or allow these functions to be called only by the MoC, for example, but I think it's not secure enough.

**Comment by akolotov** [comment]
What if we do in the same manner how it exists now:
So, instead of 
```solidity
    address public constant bridgeContract = 0x0000000000000000000000000000000000000000;
```
we will have
```solidity
    mapping (address => bool) public bridgeContracts;
    bridgeContracts["0x1...a"] = true;
    bridgeContracts["0x2...b"] = true;
    bridgeContracts["0x3...c"] = true;
```

**Comment by varasev** [comment]
Yes, we can make the addresses hardcoded. In the case when we want to add some new bridge contract, we can implement `addBridgeContract` that can be called by anyone but with hardcoded new address and can be called only once. For example:

```
function addBridgeContract() public {
    address newContract = "0x4...d";
    require(bridgeContracts[newContract] == false);
    bridgeContracts[newContract] = true;
}
```

The same is for `removeBridgeContract`:

```
function removeBridgeContract() public {
    address contractToRemove = "0x1...a";
    require(bridgeContracts[contractToRemove] == true);
    bridgeContracts[contractToRemove] = false;
}
```

`addBridgeContract`/ `removeBridgeContract` function will have to be called after RewardByBlock's implementation is upgraded.

**Comment by varasev** [comment]
To not to change the state of RewardByBlock contract we could just add the next getter in its implementation:

```
function isBridgeContract(address _addr) public pure returns(bool) {
    if (_addr == "0x1...a") {
        return true;
    }
    if (_addr == "0x2...b") {
        return true;
    }
    if (_addr == "0x3...c") {
        return true;
    }
    return false;
}
```

**Comment by akolotov** [comment]
It is OK for me. How about ideas for implementation of `mintedByBridge`?

**Comment by varasev** [comment]
I'll think about it and implement soon. There shouldn't be any difficulties.

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/poa-network-consensus-contracts/pull/201.
