### ISSUE TITLE
Zipcode should not be stored as in Integer datatype, i.e. uint256

### ISSUE THREAD

**Issue by johnnynuuma** [poanetwork/poa-network-consensus-contracts#45]
n ValidatorMetadata.sol, I see:
struct Validator {
      ..
        uint256 zipcode;
     ...
    }
zipcode should not be stored as an Int ( doesn't support leading zeros and for Internationalization purposes ... even US has alphanumeric with extension for example  94609-1314 )

**Comment by vbaranov** [comment]
@varasev could we close it as we already merged these changes for `ValidatorMetadata` contract?
