### ISSUE TITLE
License status

### ISSUE THREAD

**Issue by chebykin** [poanetwork/poa-network-consensus-contracts#51]
Hi! Do you have a license defined for this repository? I want to use these contracts with another project.

**Comment by igorbarinov** [comment]
Thank you. I've added GPL3
@chebykin where do you plan to use it? Just curious

**Comment by chebykin** [comment]
@igorbarinov, Thank you!

We're planning to build some mysterious 😀  concepts about validation and some other things. It's hard for me to express this in a clear way now, probably will do this later. So we had agreed that we should try to use some parts of POA.Network project as had found that it is the maturest one to build an ethereum-like network we want.

You guys are doing a great project! Thanks!

**Comment by igorbarinov** [comment]
@chebykin thank you.

Sounds good. Let us know if you have any questions about our governance model.
