### ISSUE TITLE
changeRequest and changeRequestForValidator functions should check zipcode

### ISSUE THREAD

**Issue by varasev** [poanetwork/poa-network-consensus-contracts#55]
In ValidatorMetadata.sol these functions should check _zipcode for zero because we see the same condition in onlyIfChangeExist function:

```
function onlyIfChangeExist(address _miningKey) public view returns(bool) {
    return pendingChanges[_miningKey].zipcode > 0;
}

```
I suggest to use

`require(_zipcode > 0);`

at the beginning of changeRequest and changeRequestForValidator.

**Comment by rstormsf** [comment]
I'm not clear on that one.

**Comment by varasev** [comment]
If we call changeRequest or changeRequestForValidator with _zipcode = 0, then onlyIfChangeExist function will think, that the pending change doesn't exist for a given _miningKey.

Therefore I propose to use

`require(_zipcode > 0);`

in changeRequest and changeRequestForValidator to exclude such situations.

Another solution is to use createdDate instead of zipcode in onlyIfChangeExist function, because createdDate always greater than zero. Example:

```
function onlyIfChangeExist(address _miningKey) public view returns(bool) {
    return pendingChanges[_miningKey].createdDate > 0;
}
```
