### ISSUE TITLE
(Fix) introduce upper limit of ballot's duration

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#60]
To prevent infinite ballots such as https://github.com/poanetwork/poa-dapps-voting/issues/100
Relates to https://github.com/poanetwork/poa-dapps-voting/issues/81

14 days sounds good for me

**Comment by varasev** [comment]
Done.

**Comment by varasev** [comment]
Implemented in `security-audit` branch: https://github.com/poanetwork/poa-network-consensus-contracts/tree/security-audit
