### ISSUE TITLE
(Feature) Make ValidatorMetadata upgradable

### ISSUE THREAD

**Issue by varasev** [poanetwork/poa-network-consensus-contracts#63]
ValidatorMetadata contract made upgradable. The changes are in my repo: https://github.com/varasev/poa-network-consensus-contracts/blob/master/contracts/ValidatorMetadata.sol

All the current tests are passing.

The next solution from zeppelinos (thanks!) was used: https://github.com/zeppelinos/labs/tree/master/upgradeability_using_generic_eternal_storage

It is an awesome solution to separate an implementation from a storage! Now we can change contract's implementation and keep it's storage.

We need only two additional contracts for this: https://github.com/varasev/poa-network-consensus-contracts/tree/master/contracts/eternal-storage

It is planned that EternalStorageProxy.upgradeTo function will be called from ProxyStorage contract when the voters agree with implementation changing in VotingToChangeProxyAddress contract.

We can also do this with other contracts soon.

**Comment by varasev** [comment]
The voting for ValidatorMetadata address changing has been implemented in my repo today: https://github.com/varasev/poa-network-consensus-contracts

It is assumed that validators can vote for ValidatorMetadata storage address changing and for it's implementation address changing.

All tests are successful. However, a contracts deployment (migrations/2_deploy_contract.js) has not been tested yet.

**Comment by varasev** [comment]
Detailed tests to check ValidatorMetadata upgradability are added: https://github.com/varasev/poa-network-consensus-contracts/commit/941b217ae093cbea2d6e5f5d9e5936858f1719bd

**Comment by varasev** [comment]
Travis tests status in my repo:
[![Build Status](https://travis-ci.org/varasev/poa-network-consensus-contracts.svg?branch=master)](https://travis-ci.org/varasev/poa-network-consensus-contracts)

**Comment by varasev** [comment]
A contracts deployment (migrations/2_deploy_contract.js) using a local MoC node has been tested and successful:

```
...

Writing artifacts to ./build/contracts

Using network 'sokol'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x941a7f06be9b3dcf3c88e9543d40dc9beac5b8ec3a51cc166e89ab0a2d396a8b
  Migrations: 0x16db159bcaefe7600527cd3eda605bbb083a6454
Saving successful migration to network...
  ... 0x093c4d7995c3be70560f8bc238fb193b5dbe464511402ecf3e1489713e614ae5
Saving artifacts...
Running migration: 2_deploy_contract.js
Saving successful migration to network...
  Deploying PoaNetworkConsensus...
  ... 0xec7da92d121e6fc74e00d513c326d23637c9c4a69938fb9db0a86d62c97d5e0f
  ... 0xdda4864c0d06bd06ce62dc7b2dacea574dcefd2fcea73bdf0495179b1fa75440
Saving artifacts...
  PoaNetworkConsensus: 0x31996a4f9511139733d7f1cb1b750b5a790eacd3
0x31996a4f9511139733d7f1cb1b750b5a790eacd3
  Deploying ProxyStorage...
  ... 0x1d665cae59f2a28623d47e7f82de54bc6b2e8fc4466e458c51ee2bccc99d72c1
  ProxyStorage: 0xa69295d0c01c3e72575aee5497dce3b79e588dad
  Deploying KeysManager...
  ... 0x2703bbdafd0f9bae13f95b7a1da26bda79da7bd179188c802a338ae10f5c7bec
  KeysManager: 0x64a27ab364f4cdef0974ff849756c0320c0dd037
  Deploying BallotsStorage...
  ... 0x4c7883a67d198823a048921433879bdf244c1aa06e7b03ce1185c0970f8a9d91
  BallotsStorage: 0xcacd72c280c9201434dc5c89b0314d83ac4a02f3
  Deploying ValidatorMetadata...
  ... 0xb9f9047a6cafe7b1664c2eddb47bfb25c5d78a4319d85be9a30e9e0e6ff7326e
  ValidatorMetadata: 0x06b70f69051f7bbbd2ae2ae3ce8067fd3b842184
  Deploying EternalStorageProxy...
  ... 0x4be3c3525f477983e121f5608f2a351ee242f3500f59386f345a54a336af22bf
  EternalStorageProxy: 0x9b258da7a09a438e9c76e673014b413d7bec960c
  Deploying VotingToChangeKeys...
  ... 0x44036ad124ce6382bb574b590607280891646de9881087c7a6daa140b010529d
  VotingToChangeKeys: 0x20d85f31d3a45292999d6de6868507c5520c60c1
  Deploying VotingToChangeMinThreshold...
  ... 0x5496a3957d1e2d8d5a1c3ee334404e8df2f20bf576f18bb30511ac7a9dae9679
  VotingToChangeMinThreshold: 0x748966918fd5b57322890508f5fd02f60e56ea5b
  Deploying VotingToChangeProxyAddress...
  ... 0xa9e3ca31942bd7da68a274117ad7e2e626ad507bb8fe56a34d1b6e1cf0493ab5
  VotingToChangeProxyAddress: 0x700d547b48d8b3fe9836676dbf4c91c715809f10
  ... 0xa020f03642463f791136b089929747ecd9b5ef4b4ad05bc2c501cba07dedf781
  ... 0x5460fa616745b3994d504b34ebdff463c6864dae0c1d6f9e161516924dfe421e
  ... 0x6bc270741df0425887a2e1cf7f10d738cc5465a8e2bab46f5467552a592af472
null
Done
ADDRESSES:
 VotingToChangeKeys.address 0x20d85f31d3a45292999d6de6868507c5520c60c1

      VotingToChangeMinThreshold.address 0x748966918fd5b57322890508f5fd02f60e56ea5b

      VotingToChangeProxyAddress.address 0x700d547b48d8b3fe9836676dbf4c91c715809f10

      BallotsStorage.address 0xcacd72c280c9201434dc5c89b0314d83ac4a02f3

      KeysManager.address 0x64a27ab364f4cdef0974ff849756c0320c0dd037

      ValidatorMetadata.address 0x9b258da7a09a438e9c76e673014b413d7bec960c

      ProxyStorage.address 0xa69295d0c01c3e72575aee5497dce3b79e588dad
```

**Comment by vbaranov** [comment]
Let's test first 4 basic scenarios https://github.com/poanetwork/poa-test-setup#basic-scenarios with updated set of contracts

**Comment by varasev** [comment]
@vbaranov, sure, I'll let you know when it's ready.

**Comment by varasev** [comment]
Demo branch of **poa-network-consensus-contracts** repo also updated including tests: https://github.com/varasev/poa-network-consensus-contracts/commits/demo

**Comment by varasev** [comment]
The set of poa-test-setup scenarios that use new ValidatorMetadata are successful: https://github.com/varasev/poa-test-setup

During the testing on Ubuntu it was revealed that it is necessary to additionally install Google Chrome and X virtual framebuffer before Launch Ceremony on Ubuntu: https://github.com/poanetwork/poa-test-setup/issues/15#issuecomment-377131489

I'll create a pull request with a new README for https://github.com/poanetwork/poa-test-setup repo.
