### ISSUE TITLE
ValidatorMetadata and it's storage address in contracts.json

### ISSUE THREAD

**Issue by varasev** [poanetwork/poa-network-consensus-contracts#64]
@rstormsf @vbaranov 

migrations/2_deploy_contract.js saves contracts addresses into contracts.json.

Now we have ValidatorMetadata contract address and EternalStorageProxy address: https://github.com/varasev/poa-network-consensus-contracts/commit/d9aa31ea570caa81c3276ac70341745883055102

Is it OK? Or we have to save only EternalStorageProxy address?

For example:

```
let contracts = {
  ...
  "METADATA_ADDRESS": EternalStorageProxy.address,
  ...
}
```

instead of

```
let contracts = {
  ...
  "METADATA_ADDRESS": ValidatorMetadata.address,
  "ETERNAL_STORAGE_PROXY": EternalStorageProxy.address,
  ...
}
```

I think the former is better because we need to know only the storage address to use ValidatorMetadata.

**Comment by rstormsf** [comment]
I think METADATA_ADDRESS should be `EternalStorageProxy.address`

**Comment by varasev** [comment]
@vbaranov, what can you say?

**Comment by vbaranov** [comment]
I prefer not to mix and to list all set of consensus contracts in `contracts.json`. Moreover, we copy this set of contracts to `chain-spec` repo https://github.com/poanetwork/poa-chain-spec/blob/core/contracts.json. We could change mapping on DApps side. But if you, guys, insist I will not prevent. The majority is on your side.

**Comment by varasev** [comment]
Ok, I will write storage contract address to METADATA_ADDRESS because I think it is more transparently for dApps.
