### ISSUE TITLE
(Update) Deploy new upgradable ValidatorMetadata contracts to Sokol network

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#68]
Deploy new upgradable ValidatorMetadata storage and implementation contracts and new ProxyStorage to Sokol network and provide addresses. 
Relates to https://github.com/poanetwork/poa-chain-spec/pull/62.

**Comment by varasev** [comment]
@rstormsf @vbaranov 

Deploy has been made to Sokol. New Addresses:

**ProxyStorage:** 0x36c616b2267a9950e9337af15533ac65608d1427
**BallotsStorage:** 0xb3fa07c07afedaf3931c809fbab22069b3f997d2
**ValidatorMetadata:** 0xaed535899f960e17035781c36c77ea03ca8c66f5

@rstormsf you have a voting key, so please call ProxyStorage.initializeAddresses:

```
initializeAddresses(
0x1aa02bd52fe418ac70263351282f66f1dacf898c,
0xc40cdf254a4a35498aa84f35e9842c110729a2a0,
0x700db8ba3128087f3b23f60de4bc3179bafa467d,
0x0aa4a75549757a90f62f88b3b96b69bead2db0ff,
0xb3fa07c07afedaf3931c809fbab22069b3f997d2,
0xaed535899f960e17035781c36c77ea03ca8c66f5
)
```

**Comment by rstormsf** [comment]
Please explain what needs to be done. It's not clear.

**Comment by varasev** [comment]
@rstormsf @vbaranov

I've created migration feature in ValidatorMetadata: https://github.com/varasev/poa-network-consensus-contracts/commit/98ad8185247c58b52eb631b61106f4c2b2c5926f

To do metadata migration to the new contract in Sokol we should run scripts/migrateMetadata.js as shown below:

```
NETWORK=sokol METADATA_OLD_ADDRESS=0x1ce9ad5614d3e00b88affdfa64e65e52f2e4e0f4 METADATA_NEW_ADDRESS=0xcfc7412c6e02b180a3304d8072f3c323d4abdd94 node migrateMetadata 
```

METADATA_OLD_ADDRESS is an address of the current ValidatorMetadata contract in Sokol.
METADATA_NEW_ADDRESS is an address of newly deployed ValidatorMetadata contract in Sokol.

I've tested this script in Sokol - it works fine:

```
Migration...
0xE8DDc5c7A2d2F0D7a9798459c0104fDf5E987ACA...success
0x82e4e61e7f5139ff0a4157A5Bc687eF42294c248...success
0x23468dB7f4b8Ff4924B0709aB7Ae0971B3Bc8d28...success
0xA0B0D4cCF483b000F0aF59C47A1944668477b941...success
0xe2ac1c6843A33f81aE4935E5EF1277a392990381...success
0xde88a1a783b29a0b476BE28beEF38B4A85c0e024...success
0x4E20226355b4464Cf8f3b67Fc318b753A7c125B3...success
0xdb1207770E0a4258D7A4Ce49aB037f92564feA85...success
0xeD2ACEb63Eb7928e67c854C24F61cF41db311c36...success
0x4Ca0f1a7B5a2723A9094B7706BaA23C2B8BD46A0...success
0x5B2cf18296B2ABf23288Ef2F9A09C6E1275311e5...success
0x58baD7Cf29428c3D17Cb859f5C580D3C25F134CD...success
0xcBbcd5Ac86F9a50e13313633B262e16f695a90c1...success
0x0b55FdBa9e288C23cF3EB04c6f237D3bd0f751d6...success
0x46bc76E617E72cE6658C199E222C07cBa2Fb5aEc...success
0xf74769d9FFe1Cd17F20b283995CF9e7fA2A262ed...success
0x063fE3bAFcf93D099dd7E09b3372641dc5E04e15...success
0x7BD556B838a9E330a815a53EF39e04Ff2fDf2392...success
```

ValidatorMetadata I used for these tests has the next address in Sokol: 0x6d23b4f00fedb122ed823cb0393d8656d8f78b3c 

You can see that the information about all validators is filled correctly.

**Comment by varasev** [comment]
@rstormsf please call **ProxyStorage.initializeAddresses** in Sokol as shown below:

```
initializeAddresses(
"0x1aa02bd52fe418ac70263351282f66f1dacf898c",
"0xc40cdf254a4a35498aa84f35e9842c110729a2a0",
"0x700db8ba3128087f3b23f60de4bc3179bafa467d",
"0x0aa4a75549757a90f62f88b3b96b69bead2db0ff",
"0x27e7d2572aa37bec2ed30795f2fabccda4781f86",
"0xcfc7412c6e02b180a3304d8072f3c323d4abdd94"
)
```

ProxyStorage address in Sokol is **0x36c616b2267a9950e9337af15533ac65608d1427**

ProxyStorage ABI for this action:

```json
[{"constant":false,"inputs":[{"name":"_keysManager","type":"address"},{"name":"_votingToChangeKeys","type":"address"},{"name":"_votingToChangeMinThreshold","type":"address"},{"name":"_votingToChangeProxy","type":"address"},{"name":"_ballotsStorage","type":"address"},{"name":"_validatorMetadataEternalStorage","type":"address"}],"name":"initializeAddresses","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}]
```

After that I will run **scripts/migrateMetadata.js** for newly deployed ValidatorMetadata.

**Comment by rstormsf** [comment]
the tx failed:
https://sokol-explorer.poa.network/tx/0x5da88691bcdb65fc72a1e2f832c4d0763b3248adf778edcf55ab0fa164aa83b5

**Comment by varasev** [comment]
@rstormsf repeat with your mining key please.

**Comment by varasev** [comment]
Metadata migration has been done successfully in Sokol network.

One can see the result at https://varasev.github.io - this Validators dApp is connected to the new ValidatorMetadata contract.

Validators' metadata is the same as in the current dApp https://sokol-validators.poa.network/ connected to the old metadata contract.

I'll repeat `poa-test-setup` steps again to make sure everything is OK and then create PR for `poa-chain-spec` repo (sokol branch) to update ValidatorMetadata and ProxyStorage ABIs and addresses.
