### ISSUE TITLE
(Feature) Make BallotsStorage and VotingToChange* upgradable

### ISSUE THREAD

**Issue by varasev** [poanetwork/poa-network-consensus-contracts#75]
I'll use the same solution as described in https://github.com/poanetwork/poa-network-consensus-contracts/issues/63. I.e. now we have EternalStorage https://github.com/poanetwork/poa-network-consensus-contracts/tree/master/contracts/eternal-storage used for `ValidatorMetadata` contract and we can use it for voting contracts too.

**Comment by varasev** [comment]
I made a commit related to `VotingToChangeMinThreshold` upgradable in my repository today: https://github.com/varasev/poa-network-consensus-contracts/commit/d65a94d65ad375d52c111225ac2023b395aa6f4a

Without migration function yet.

All tests are successful: https://travis-ci.org/varasev/poa-network-consensus-contracts/builds/373436485

**Comment by varasev** [comment]
`VotingToChangeMinThreshold` migrate functionality was added and tested today: https://github.com/varasev/poa-network-consensus-contracts/commit/c397569089449ff018f5b07aea5d2bcb9a6b97c1

**Comment by varasev** [comment]
I made a commit related to `VotingToChangeProxyAddress` upgradable in my repository today: https://github.com/varasev/poa-network-consensus-contracts/commit/2736f7eeda89dde7834619738d361591a7f8f5db

Without migration function yet.

All tests are successful: https://travis-ci.org/varasev/poa-network-consensus-contracts/builds/374496547

**Comment by rstormsf** [comment]
let us know if @vbaranov or I can help  you with anything

**Comment by varasev** [comment]
`VotingToChangeProxyAddress` migrate functionality was added and tested today: https://github.com/varasev/poa-network-consensus-contracts/commit/02a50891f0dbf0a872a9eb53edb200e7a0c86e49
