### ISSUE TITLE
(Security) Known vulnerability in `hoek@4.2.0` dependency

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#85]
**Problem**: `ethereumjs-testrpc` has a dependency with a known vulnerability

![screen shot 2018-05-18 at 17 18 53](https://user-images.githubusercontent.com/4341812/40240848-363558c6-5ac2-11e8-8ee9-63bfe3f28a7a.png)

**Solution**: migrate from `ethereumjs-testrpc@6.0.3` to the latest version of `ganache-cli`

**Comment by varasev** [comment]
`ganache-cli` successful tests results: https://travis-ci.org/poanetwork/poa-network-consensus-contracts/builds/382180878

**Comment by varasev** [comment]
@vbaranov, please recheck that. There shouldn't be any vulnerability found now.

**Comment by vbaranov** [comment]
@varasev I don't see `hoek@4.2.0` dependency anymore. Could be closed.
