### ISSUE TITLE
(Tests) Add unit tests for additional emission and block reward smart-contracts

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#86]
**Problem**: `VotingToManageEmissionFunds`, `EmissionFunds` and `BlockReward` contracts are not covered with unit tests

**Solution**: extend unit tests to cover these contracts

**Comment by varasev** [comment]
Ok, it's in progress.

**Comment by varasev** [comment]
Unit tests have been extended in https://github.com/poanetwork/poa-network-consensus-contracts/pull/105.
