### ISSUE TITLE
(Feature) new ballot type: add 3 keys

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#92]
**Problem**: The current validators should create 3 ballots to add a completely new validator to consensus: 1 ballot for each key. Validators should make 3 times more actions to create, vote and finalize it instead of doing this stuff in frames of one ballot.

**Solution**: Create new ballot type to add 3 keys in `/VotingToChangeKeys.sol`

**Comment by varasev** [comment]
`VotingToChangeKeys` contract has been supplemented by new `createBallotToAddNewValidator` method that creates a ballot to add three keys (mining/voting/payout) at once: https://github.com/varasev/poa-network-consensus-contracts/blob/57fd4105075c2fb87633c73e75a3baacb7613555/contracts/VotingToChangeKeys.sol#L140-L163

In this case, finalization occurs inside `_finalizeAdding` method: https://github.com/varasev/poa-network-consensus-contracts/blob/57fd4105075c2fb87633c73e75a3baacb7613555/contracts/VotingToChangeKeys.sol#L234-L244

I assume that a new validator can also be added by `createBallot` method to support the current principle of separate keys adding: https://github.com/varasev/poa-network-consensus-contracts/blob/57fd4105075c2fb87633c73e75a3baacb7613555/contracts/VotingToChangeKeys.sol#L117-L138

`createBallotToAddNewValidator` method has also been covered by tests: https://github.com/varasev/poa-network-consensus-contracts/blob/57fd4105075c2fb87633c73e75a3baacb7613555/test/voting_to_change_keys_test.js#L143

I will create a related issue for `Governance DApp` to change its web interface accordingly.

These changes cover https://github.com/poanetwork/poa-dapps-voting/issues/83.
