### ISSUE TITLE
(Refactor) validators && pendingChanges functions could use the same subfunction inside

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#93]
**Problem**: 
implementation of 
`validators` function: https://github.com/poanetwork/poa-network-consensus-contracts/blob/security-audit/contracts/ValidatorMetadata.sol#L46
and
`pendingChanges` function: https://github.com/poanetwork/poa-network-consensus-contracts/blob/security-audit/contracts/ValidatorMetadata.sol#L70

have repeated content

**Solution**: create internal subfunction `_validators(bool _pending, address _miningKey)` instead

**Comment by varasev** [comment]
Thanks for the help with refactoring. Didn't see it with my eyes :)
