### ISSUE TITLE
MoC will never receive payment

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-network-consensus-contracts#98]
https://github.com/poanetwork/poa-network-consensus-contracts/blob/security-audit/contracts/BlockReward.sol#L47

if payout is address(0) please give reward to mining key

**Comment by varasev** [comment]
Yes, I'll fix that.

**Comment by varasev** [comment]
Fixed in https://github.com/poanetwork/poa-network-consensus-contracts/pull/105.
